const inter = Inter({ subsets: ["latin"] });
import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Intro from "@/components/intro";
import Skills from "@/components/skills";
import Header from "@/components/header";
import Manu from "@/components/manu";
import Project from "@/components/project";
import Contact from "@/components/contact";

export default function Home() {
  // https://medium.com/@ranjandsingh/snap-scroll-in-react-in-less-than-a-minute-b6ba45453b7a
  return (
    <>
      <Head>
        <title>acuvilr.one - Avril Cui&apos;s personal website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Header />
        <Manu />
          <Intro id="section1" />
          <Skills id="section2" />
          <Project id="section3" />
          <Contact />
      </main>
    </>
  );
}
