const inter = Inter({ subsets: ["latin"] });
import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Intro from "@/components/intro";
import Skills from "@/components/skills";
import Header from "@/components/header";
import Manu from "@/components/manu";
import { motion } from "framer-motion";
import { fadeIn } from "../utils/motion";
import Project from "@/components/project";
import Contact from "@/components/contact";
import { useRef } from "react";
import useScrollSnap from "react-use-scroll-snap";

export default function Home() {
  const scrollRef = useRef(null);
  useScrollSnap({ ref: scrollRef, duration: 1 });
  return (
    <>
      <Head>
        <title>acuvilr.one - Avril Cui's personal website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Header />
        <Manu />
        <div ref={scrollRef}>
          <Intro id="section1" />
          <Skills id="section2" />
          <Project id="section3" />
          <Contact />
        </div>
      </main>
    </>
  );
}
